import { useEffect, useMemo, useState } from 'react'
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { fetchTestResults } from './api'
import { Card } from './components'
import type { TestCaseResult, TestResultsSummary } from './types'

const OUTCOME_STYLE: Record<string, string> = {
  passed: 'text-emerald-400', failed: 'text-red-400', skipped: 'text-amber-400', error: 'text-red-400',
}
const OUTCOME_ICON: Record<string, string> = { passed: '✅', failed: '❌', skipped: '⚠', error: '❌' }

function moduleOf(nodeid: string): string {
  return nodeid.split('::')[0]
}

export default function TestResults() {
  const [results, setResults] = useState<TestResultsSummary | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [filter, setFilter] = useState<'all' | 'passed' | 'failed' | 'skipped'>('all')

  useEffect(() => {
    setLoading(true)
    setError(null)
    fetchTestResults()
      .then(setResults)
      .catch(err => setError((err as Error).message))
      .finally(() => setLoading(false))
  }, [])

  const byModule = useMemo(() => {
    if (!results) return []
    const counts = new Map<string, { passed: number; failed: number; skipped: number }>()
    for (const t of results.tests) {
      const mod = moduleOf(t.nodeid)
      const entry = counts.get(mod) || { passed: 0, failed: 0, skipped: 0 }
      if (t.outcome === 'passed') entry.passed++
      else if (t.outcome === 'failed' || t.outcome === 'error') entry.failed++
      else entry.skipped++
      counts.set(mod, entry)
    }
    return [...counts.entries()]
      .map(([mod, c]) => ({ module: mod.replace('tests/', '').replace('.py', ''), ...c }))
      .sort((a, b) => a.module.localeCompare(b.module))
  }, [results])

  const filteredTests: TestCaseResult[] = useMemo(() => {
    if (!results) return []
    if (filter === 'all') return results.tests
    return results.tests.filter(t =>
      filter === 'failed' ? (t.outcome === 'failed' || t.outcome === 'error') : t.outcome === filter,
    )
  }, [results, filter])

  if (loading) return <p className="text-slate-400 text-sm">Loading test results…</p>
  if (error) {
    return (
      <p className="text-amber-400 text-sm">
        Could not load test results ({error}). This file is generated by CI on every push to main —
        if you're running the dashboard locally against a fresh checkout, it may not exist yet.
      </p>
    )
  }
  if (!results) return null

  const { summary } = results
  const passed = summary.passed ?? 0
  const failed = summary.failed ?? 0
  const skipped = summary.skipped ?? 0
  const passRate = summary.total > 0 ? (passed / summary.total) * 100 : 0
  const lastUpdated = new Date(results.created * 1000).toLocaleString()

  return (
    <div className="space-y-4">
      <div>
        <h1 className="text-3xl font-bold mb-1">BCT Test Dashboard</h1>
        <p className="text-slate-400 text-sm">
          Full test suite results — regenerated and redeployed automatically on every push to main.
        </p>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
        <Card title="Total"><div className="text-2xl font-bold">{summary.total}</div></Card>
        <Card title="Passed"><div className="text-2xl font-bold text-emerald-400">{passed}</div></Card>
        <Card title="Failed"><div className="text-2xl font-bold text-red-400">{failed}</div></Card>
        <Card title="Skipped"><div className="text-2xl font-bold text-amber-400">{skipped}</div></Card>
        <Card title="Pass Rate"><div className="text-2xl font-bold">{passRate.toFixed(1)}%</div></Card>
      </div>

      <Card title="Run Info">
        <div className="grid grid-cols-2 md:grid-cols-3 gap-3 text-sm">
          <div>
            <div className="text-slate-500 text-xs">Last updated</div>
            <div className="font-semibold">{lastUpdated}</div>
          </div>
          <div>
            <div className="text-slate-500 text-xs">Total duration</div>
            <div className="font-semibold">{results.duration.toFixed(2)}s</div>
          </div>
        </div>
      </Card>

      <Card title="Results by Module">
        <div className="h-64">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={byModule} layout="vertical" margin={{ left: 40 }}>
              <CartesianGrid strokeDasharray="3 3" stroke="#334155" />
              <XAxis type="number" stroke="#94a3b8" fontSize={12} />
              <YAxis type="category" dataKey="module" stroke="#94a3b8" fontSize={11} width={150} />
              <Tooltip contentStyle={{ background: '#1e293b', border: '1px solid #334155' }} />
              <Bar dataKey="passed" stackId="a" fill="#34d399" />
              <Bar dataKey="failed" stackId="a" fill="#f87171" />
              <Bar dataKey="skipped" stackId="a" fill="#fbbf24" />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </Card>

      <Card title="Test Cases">
        <div className="flex gap-2 mb-3">
          {(['all', 'passed', 'failed', 'skipped'] as const).map(f => (
            <button
              key={f}
              onClick={() => setFilter(f)}
              className={`px-3 py-1 rounded text-xs font-medium ${
                filter === f ? 'bg-sky-600 text-white' : 'bg-slate-700 text-slate-300 hover:bg-slate-600'
              }`}
            >
              {f.charAt(0).toUpperCase() + f.slice(1)}
            </button>
          ))}
        </div>
        <div className="max-h-96 overflow-y-auto">
          <table className="w-full text-sm">
            <thead className="sticky top-0 bg-slate-800">
              <tr className="text-slate-400 text-left border-b border-slate-700">
                <th className="pb-1 pr-4">Test</th>
                <th className="pb-1 pr-4">Outcome</th>
                <th className="pb-1">Duration</th>
              </tr>
            </thead>
            <tbody>
              {filteredTests.map(t => (
                <tr key={t.nodeid} className="border-b border-slate-800">
                  <td className="py-1 pr-4 font-mono text-xs">{t.nodeid}</td>
                  <td className={`py-1 pr-4 font-semibold ${OUTCOME_STYLE[t.outcome] || ''}`}>
                    {OUTCOME_ICON[t.outcome] || ''} {t.outcome}
                  </td>
                  <td className="py-1 text-slate-400">{(t.duration * 1000).toFixed(0)}ms</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  )
}
